/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedAppLayoutImport } from './routes/_authenticated/_appLayout'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const AuthenticatedAppLayoutTodoLazyImport = createFileRoute(
  '/_authenticated/_appLayout/todo',
)()
const AuthenticatedAppLayoutAboutLazyImport = createFileRoute(
  '/_authenticated/_appLayout/about',
)()
const AuthenticatedAppLayoutOrgIndexLazyImport = createFileRoute(
  '/_authenticated/_appLayout/org/',
)()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AuthenticatedAppLayoutRoute = AuthenticatedAppLayoutImport.update({
  id: '/_appLayout',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAppLayoutTodoLazyRoute =
  AuthenticatedAppLayoutTodoLazyImport.update({
    id: '/todo',
    path: '/todo',
    getParentRoute: () => AuthenticatedAppLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/_appLayout/todo.lazy').then((d) => d.Route),
  )

const AuthenticatedAppLayoutAboutLazyRoute =
  AuthenticatedAppLayoutAboutLazyImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AuthenticatedAppLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/_appLayout/about.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedAppLayoutOrgIndexLazyRoute =
  AuthenticatedAppLayoutOrgIndexLazyImport.update({
    id: '/org/',
    path: '/org/',
    getParentRoute: () => AuthenticatedAppLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/_appLayout/org/index.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_appLayout': {
      id: '/_authenticated/_appLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedAppLayoutImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_appLayout/about': {
      id: '/_authenticated/_appLayout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAppLayoutAboutLazyImport
      parentRoute: typeof AuthenticatedAppLayoutImport
    }
    '/_authenticated/_appLayout/todo': {
      id: '/_authenticated/_appLayout/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof AuthenticatedAppLayoutTodoLazyImport
      parentRoute: typeof AuthenticatedAppLayoutImport
    }
    '/_authenticated/_appLayout/org/': {
      id: '/_authenticated/_appLayout/org/'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof AuthenticatedAppLayoutOrgIndexLazyImport
      parentRoute: typeof AuthenticatedAppLayoutImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedAppLayoutRouteChildren {
  AuthenticatedAppLayoutAboutLazyRoute: typeof AuthenticatedAppLayoutAboutLazyRoute
  AuthenticatedAppLayoutTodoLazyRoute: typeof AuthenticatedAppLayoutTodoLazyRoute
  AuthenticatedAppLayoutOrgIndexLazyRoute: typeof AuthenticatedAppLayoutOrgIndexLazyRoute
}

const AuthenticatedAppLayoutRouteChildren: AuthenticatedAppLayoutRouteChildren =
  {
    AuthenticatedAppLayoutAboutLazyRoute: AuthenticatedAppLayoutAboutLazyRoute,
    AuthenticatedAppLayoutTodoLazyRoute: AuthenticatedAppLayoutTodoLazyRoute,
    AuthenticatedAppLayoutOrgIndexLazyRoute:
      AuthenticatedAppLayoutOrgIndexLazyRoute,
  }

const AuthenticatedAppLayoutRouteWithChildren =
  AuthenticatedAppLayoutRoute._addFileChildren(
    AuthenticatedAppLayoutRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppLayoutRoute: typeof AuthenticatedAppLayoutRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppLayoutRoute: AuthenticatedAppLayoutRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '': typeof AuthenticatedAppLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/about': typeof AuthenticatedAppLayoutAboutLazyRoute
  '/todo': typeof AuthenticatedAppLayoutTodoLazyRoute
  '/org': typeof AuthenticatedAppLayoutOrgIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '': typeof AuthenticatedAppLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/about': typeof AuthenticatedAppLayoutAboutLazyRoute
  '/todo': typeof AuthenticatedAppLayoutTodoLazyRoute
  '/org': typeof AuthenticatedAppLayoutOrgIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/_appLayout': typeof AuthenticatedAppLayoutRouteWithChildren
  '/_authenticated/_appLayout/about': typeof AuthenticatedAppLayoutAboutLazyRoute
  '/_authenticated/_appLayout/todo': typeof AuthenticatedAppLayoutTodoLazyRoute
  '/_authenticated/_appLayout/org/': typeof AuthenticatedAppLayoutOrgIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/login' | '/about' | '/todo' | '/org'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/login' | '/about' | '/todo' | '/org'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/_appLayout'
    | '/_authenticated/_appLayout/about'
    | '/_authenticated/_appLayout/todo'
    | '/_authenticated/_appLayout/org/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_appLayout"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authenticated/_appLayout": {
      "filePath": "_authenticated/_appLayout.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_appLayout/about",
        "/_authenticated/_appLayout/todo",
        "/_authenticated/_appLayout/org/"
      ]
    },
    "/_authenticated/_appLayout/about": {
      "filePath": "_authenticated/_appLayout/about.lazy.tsx",
      "parent": "/_authenticated/_appLayout"
    },
    "/_authenticated/_appLayout/todo": {
      "filePath": "_authenticated/_appLayout/todo.lazy.tsx",
      "parent": "/_authenticated/_appLayout"
    },
    "/_authenticated/_appLayout/org/": {
      "filePath": "_authenticated/_appLayout/org/index.lazy.tsx",
      "parent": "/_authenticated/_appLayout"
    }
  }
}
ROUTE_MANIFEST_END */
