name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: npm run build

      - name: Deploy to Vercel (Production)
        if: github.ref == 'refs/heads/main'
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}

      # - name: Deploy to Vercel (Staging)
      #   if: github.ref == 'refs/heads/staging'
      #   env:
      #     VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      #     VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
      #   run: npx vercel --token ${{ secrets.VERCEL_TOKEN }}